import { CachedSchemas, Method } from './types';

export const rootName = 'API';

export const bannerComment = `/* tslint:disable */
/**
 * This file was automatically generated by fastify-extract-definitions.
 * DO NOT MODIFY IT BY HAND. Instead, modify the fastify routes schemas
 * and re-run project to regenerate this file.
 */\n
`;

export const bannerImports = `import {
  ContextConfigDefault,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerDefault,
  RouteHandlerMethod,
} from 'fastify';
import { RouteGenericInterface } from 'fastify/types/route';

export type Handler<
  RouteGeneric extends RouteGenericInterface = RouteGenericInterface,
  ContextConfig = ContextConfigDefault
> = RouteHandlerMethod<
  RawServerDefault,
  RawRequestDefaultExpression,
  RawReplyDefaultExpression,
  RouteGeneric,
  ContextConfig
>;\n
`;

export const cachedMethods: Record<
  Method,
  { capitalized: string; uppercase: string }
> = {
  delete: { capitalized: 'Delete', uppercase: 'DELETE' },
  get: { capitalized: 'Get', uppercase: 'GET' },
  head: { capitalized: 'Head', uppercase: 'HEAD' },
  options: { capitalized: 'Options', uppercase: 'OPTIONS' },
  patch: { capitalized: 'Patch', uppercase: 'PATCH' },
  post: { capitalized: 'Post', uppercase: 'POST' },
  put: { capitalized: 'Put', uppercase: 'PUT' },
};

export const cachedSchemas: CachedSchemas = [
  { name: 'querystring', capitalized: 'Querystring' },
  { name: 'params', capitalized: 'Params' },
  { name: 'headers', capitalized: 'Headers' },
  { name: 'response', capitalized: 'Reply' },
];

export const cachedSchemasWithBody: CachedSchemas = [
  { name: 'body', capitalized: 'Body' },
  ...cachedSchemas,
];

export const methodsWithBody: Method[] = ['post', 'put', 'patch'];
